# Generated by Django 4.2.16 on 2024-11-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rapoDB',
            new_name='userTable',
        ),
    ]
